### ISSUE TITLE
Async Scripts

### ISSUE THREAD

**Issue by yconoclast** [jekyll/jekyll-gist#40] opened 2017-01-24 20:50 UTC
Would it be possible to generate an async script, to not block the page?

<script async src="https://gist.github.com/parkr/c08ee0f2726fd0e3909d.js"></script>

**Comment by pathawks** [comment] 2017-01-24 20:57
No, it is not currently possible.

Duplicate of #25.

**Closed by pathawks** 2017-01-24 20:57 UTC
